version: "3.9"
services:
  app:
    build: .
    env_file:
      - .env
    container_name: carart-app-local
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://user:password@dbhost:3306/dbname
    volumes:
      # Lokálne volumes pre testovanie
      - ./data:/app/data
      - ./data/uploads:/app/data/uploads
    ports:
      - "3000:3000"
