version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    container_name: carart-app-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://user:password@dbhost:3306/dbname
    networks:
      - web
    volumes:
      - /mnt/HC_Volume_103599864/projects/carart:/app/data
      - /mnt/HC_Volume_103599864/projects/carart/uploads:/app/data/uploads
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./next.config.ts:/app/next.config.ts
      - ./tailwind.config.ts:/app/tailwind.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./postcss.config.mjs:/app/postcss.config.mjs
    ports:
      - "3000:3000"

networks:
  web:
    external: true
